services:
  postgres:
    image: postgres:15
    container_name: restaurant_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: swain@123
      POSTGRES_DB: restaurant_management
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # app:
  #   build: .
  #   container_name: restaurant_app
  #   restart: always
  #   depends_on:
  #     - postgres
  #   environment:
  #     DB_HOST: postgres
  #     DB_PORT: 5432
  #     DB_USER: postgres
  #     DB_PASSWORD: swain@123
  #     DB_NAME: restaurant_management
  #   ports:
  #     - "8080:8080"
  #   volumes:
  #     - .:/app
  #   working_dir: /app
  #   command: go build . && ./app

volumes:
  postgres_data:
